### ISSUE TITLE
Make giithub discoverability better

### ISSUE THREAD

**Issue by MylesBorins** [google/node-sec-roadmap#15]
Currently you have to dig down to the errata. It might be nice to have a something more prominent, I'll submit a PR with an option soon

**Comment by mikesamuel** [comment]
The bottom of https://nodesecroadmap.fyi/ says

> You can browse the supporting code via github.com/google/node-sec-roadmap/.

**Comment by MylesBorins** [comment]
I'm imaging either a link right below the search bar or something at the top of the COVER. FWIW I did not notice that specific link regarding browsing the support code until looking at the first page multiple times.

What would be great is that if anyone reading the book online spots errata or has something to add it should be easy to figure out how to get started with submitting a PR

**Comment by mikesamuel** [comment]
That's a good idea I think we could add a github link to the links menu.  The PDF download link is specified in 

https://github.com/google/node-sec-roadmap/blob/f82c5ce13a3d864e461d0a11f307bda565b75c85/book.json.withcomments#L27-L39
